version: '3.8'

services:
  dbpostgresql:
    image: postgres
    container_name: postgresDatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=url-shortener

  url-shortener-backend:
    image: url-shortener/url-shortener-backend
    build:
      context: .
      dockerfile: ./url-shortener-backend/Dockerfile
      args:
        JAR_FILE_PATH: ./url-shortener-backend/build/libs/*.jar
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql

volumes:
  db-data: