version: '3.8'

services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: 
      - db-data:/data/db

  url-shortener-backend:
    image: url-shortener/url-shortener-backend
    build:
      context: .
      dockerfile: ./url-shortener-backend/Dockerfile
      args:
        JAR_FILE_PATH: ./url-shortener-backend/build/libs/*.jar
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root 
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo-db:27017/
    depends_on:
      - mongo-db 

volumes: 
  db-data:
