spring:
  data:
    mongodb:
      host: mongo-db
      port: 27017
      database: url
      username: root
      password: password
      auto-index-creation: true
      authentication-database: admin

springdoc:
  swagger-ui:
    path: /api