-- liquibase formatted sql

-- changeset pznojek:1699532747549_create_user

-- create table

create table users (
	ID BIGINT generated by default as identity primary key,
	EMAIL VARCHAR(255) not null,
	PASSWORD VARCHAR(255) not null,
	INSERTED_AT TIMESTAMP not null,
	UPDATED_AT TIMESTAMP
);