-- liquibase formatted sql

-- changeset pznojek:1699563970412_change_pk_user

-- alter table

ALTER TABLE USERS DROP COLUMN ID;
ALTER TABLE USERS ADD COLUMN ID UUID NOT NULL UNIQUE;
ALTER TABLE USERS ADD PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT email_unique UNIQUE (EMAIL);